from __future__ import annotations


EVIDENCE_SUFFICIENCY_CONTRACT_VERSION = "1"
MANDATORY_EVIDENCE_BASES = {
    "ACCEPTANCE_CRITERION_UNMET",
    "ACTUAL_CONTRADICTION",
    "EXPLICIT_PROVENANCE_CONTRACT",
    "SAFETY_AUTHORITY_REQUIREMENT",
}
EVIDENCE_THRESHOLD_CONFLICT_INVARIANTS = (
    "ACCEPTANCE_MET_CANNOT_BE_REOPENED_FOR_OPTIONAL_EVIDENCE",
    "MANDATORY_EVIDENCE_REQUIRES_ALLOWED_BASIS",
    "MANDATORY_EVIDENCE_REQUIRES_EXACT_SOURCE_EVIDENCE",
    "OPTIONAL_EVIDENCE_CANNOT_DELAY_IMPLEMENTABLE_ORIGINAL_WORK",
    "REVIEWER_CANNOT_STRENGTHEN_TASK_ACCEPTANCE_CRITERIA",
)
